### ISSUE TITLE
config psram in vscode platformio

### ISSUE THREAD

**Issue by icsHaLl** [janick/WT32-SqLn#11]
Hello Janick

I used board wt32-sc01-plus

Can you help me to configuration platformio.ini file ?

I spend time to configuration vscode -> plateformio to use psram but it is not working.

this is my configuration file

File platformio.ini
; [env:WT32-SC01-PLUS]
[env:esp32s3box]
platform = espressif32
board = esp32s3box
framework = arduino
upload_port = COM22
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.arduino.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
    -DCONFIG_SPIRAM_CACHE_WORKAROUND=1
    
  board_upload.flash_size = 16MB
lib_deps = 
	SPI
	lvgl/lv_arduino@^3.0.1
	lovyan03/LovyanGFX@^1.1.9
	bblanchon/ArduinoJson@^6.21.3

my code
float psramsize;
void setup(void)
{
  SERIALBEGIN(_buad);
  // init_sdcard();                                                                              
  lv_driver_tft();

  multi_heap_info_t info;    
heap_caps_get_info(&info, MALLOC_CAP_SPIRAM);
  psramInit() ? Serial.println("\nThe PSRAM is correctly initialized") : Serial.println("\nPSRAM does not work");
}
unsigned long _ms = false;
void loop()
{
  lv_task_handler();
  if( millis() > _ms ){
    _ms = millis() + 3000;
    const float use_heap_memory = 100 - (static_cast<float>(esp_get_free_heap_size())/ ESP.getHeapSize() ) * 100;
    DEBUG_PRINTF("heap memory using : %.2f %%", use_heap_memory );
    DEBUG_PRINTF("\tpsram : %d/%d\n", ESP.getFreePsram(), ESP.getPsramSize());
  }
  delay(5);
}

Thank you so much.

**Comment by janick** [comment]
I am sorry but I have zero experience with platformio. I only use IDF and Arduino.

I can help with your C/C++ coding but not the IDE itself or its configuration.

**Comment by icsHaLl** [comment]
Thank you so much @janick
