### ISSUE TITLE
OTA problem

### ISSUE THREAD

**Issue by AnouarBourja** [janick/WT32-SqLn#12]
Hello sir i have WT32 and squareline i would like to run the squareline exported code on my WT32 but when i follow your instructions it says that i need to work with OTA, i do not know if i can skip this step or disable OTA in your peoject so that i just run simple sqaureline project on WT32 and if you have another way to do that i will be glad to show me.

Thanks.

**Comment by janick** [comment]
OTA is entirely optional. It can be safely skipped or removed.

**Comment by AnouarBourja** [comment]
that means i can build the project by skiping the SSL certification Wifi and OTA settings ? i just want to run a simple project built using squareline if so can you tell me how to disable the OTA and SSL cert and Wifi configuration as it is requested when building the project.

Thanks.

**Comment by janick** [comment]
Yes. They are just strings that can contain junk if not used. Just use whatever is in there right now. Even if you happen to trigger OTA, it will simply not find a WiFi access point to connect to and fail without changing anything.

Skip step 2 (creating a certificate), and when editing the secrets.h file, delete line 33 to create a valid string literal.

If you are not going to use OTA, you might want to change the partition if you need more space for your program or data.
