### ISSUE TITLE
USB C Programing with a poorly designed jack

### ISSUE THREAD

**Issue by audovoice** [janick/WT32-SqLn#14]
This may not be the best forum to post this but this is something that clearly caused an enormous amount of frustration. 

I got the WT32-SC01 not the plus. But they visually seem to be the same surface mounted port. 
I had the same issues with the com port not showing up. The board would power up. But not show up as a port I could program to. 

Fortunately I took the stupid approach and just forced it in harder. It was more force than seems reasonable. There was an audible click and the plug went in another fraction of a milometer. This is definitely not a typical thing for USB C: a click when fully seated, but this component seems to be that way. 

It showed up at a com port. And I was able to program it as a esp32 wrover kit. 

I still can't figure out how to get everything working. As there are few examples, but I guess that is the downside to a lesser known board. 

Thank you for making this tutorial to help people.

**Comment by janick** [comment]
Most welcomed.
