### ISSUE TITLE
Demo Squareline Project

### ISSUE THREAD

**Issue by Seneda** [janick/WT32-SqLn#16]
Thanks for the useful repo. In the readme it says : 

>5. Build the demo application using the command idf.py build

Where is the demo UI? Is there supposed to be some demo squareline files inside main/ui?

**Comment by janick** [comment]
See the section titled "SquareLine Studio" just above it

**Comment by Seneda** [comment]
Ah i see. I think i misunderstood and thought that the example was part of squareline studio not in this repo. Thanks for your help
