### ISSUE TITLE
Which type/norm of socket is the debug connector of WT32-SC01 Plus

### ISSUE THREAD

**Issue by jberteld** [janick/WT32-SqLn#17]
Maybe some of you knows the answer:
Own a WT32-SC01 Plus. Question: Which type/norm of socket is the debug connector. Tried to find it out but no success up to now ...

**Comment by janick** [comment]
They are mentioned in the README file:

[7-pin MX1.25 PicoBlade dongles](https://www.aliexpress.us/item/3256804401152079.html)

Get some 8-pin ones at the same time for the GPIO port.

**Comment by jberteld** [comment]
Thanks Janick - I just ordered some for fuure use!
