### ISSUE TITLE
Looks great - case

### ISSUE THREAD

**Issue by marc-gist** [janick/WT32-SqLn#2]
Found your repository, your work and detail in this github page is awesome. thank you.
two things:
1. would you consider sharing your step file for the 3d case?
2. have you see the openHASP project that utilizes this device? openhasp.com/ its come a long way!

**Comment by janick** [comment]
Thank you.

1. Aren't the STL files sufficient? It's on [TinkerCAD](https://www.tinkercad.com/things/iT3zwHhoBr6?sharecode=e5QEo8DHE-eMPz_nMS6vxKNyQ0gv-TMMYveJiBz_MFw). Please don't mind the disorganized way it is put together. I'm no 3D designer. Things that need fixing:
  - It need to be 2mm deeper
  - The clips on the back panel need to be reinforced at the base. I already broke two
  - The shelf for the switch isn't big enough
  - Need to lengthen the posts holding the charger module so they can be melted down to hold the module in place
  
2. Thank you for the pointer! I was starting to think about using it for small control panels for my HA instance (I already have a tablet directly connected to HA as a main wall panel).

**Comment by marc-gist** [comment]
Thanks! I'll take a look at TinkerCAD.

Also, where did you get that USB-C Serial programmer!??

**Comment by janick** [comment]
See the [What You'll Need](https://github.com/janick/WT32-SqLn#what-youll-need) section. It has purchase links to everything. The link for the serial programmer lands you on a listing where you can chose your connector factor.

**Comment by janick** [comment]
Just updated TinkerCad design to fix the issues with the case. Sending to production to test.

**Comment by janick** [comment]
The new case fits the battery and the switch very well, as well as allowing easy mounting of the charger module.

However the lid is not fitting very well so one more iteration...

**Comment by janick** [comment]
I have removed my case as PrintMinion was kind enough to create a great hand-held case at my suggestion.

https://cults3d.com/en/design-collections/printminion/various-cases-for-wt32-sc01-plus-by-wireless-tag
