### ISSUE TITLE
Failed build: LCD_CAM_LCD_UPDATE_REG

### ISSUE THREAD

**Issue by Moktarino** [janick/WT32-SqLn#7]
Started fresh with everything today, getting this error trying to build:

`/home/me/git/WT32-SqLn/components/LovyanGFX/src/lgfx/v1/platforms/esp32s3/Bus_Parallel8.cpp: In member function 'virtual void lgfx::v1::Bus_Parallel8::writeBytes(const uint8_t*, uint32_t, bool, bool)':
/home/me/git/WT32-SqLn/components/LovyanGFX/src/lgfx/v1/platforms/esp32s3/Bus_Parallel8.cpp:354:70: error: 'LCD_CAM_LCD_UPDATE_REG' was not declared in this scope; did you mean 'LCD_CAM_LCD_UPDATE_M'?
  
354 |       *reg_lcd_user = LCD_CAM_LCD_CMD | LCD_CAM_LCD_CMD_2_CYCLE_EN | LCD_CAM_LCD_UPDATE_REG | LCD_CAM_LCD_START;`

The same error occurs with Bus_Parallel16.cpp.
I'm building on Ubuntu 22.10 with Python 3.10.7
I've tried the earlier versions of LovyanGFX (1.1.15, 1.1.16) to no avail.

**Comment by janick** [comment]
I ran into the same error too. It disappeared when I reverted esp-idf to 5.0.2 -- looks like the IDF installer always uses the head of the main branch, not a release tag.

**Comment by Moktarino** [comment]
Now I'm getting this error: 
`WT32-SqLn/components/LovyanGFX/src/lgfx/v1/platforms/esp32/common.cpp:646:14: error: 'struct i2c_dev_t' has no member named 'comd0'; did you mean 'comd'?
`
idf version is: ESP-IDF v5.0.2-376-g24b9d38a24

I used these commands to roll back:
git checkout release/v5.0
git submodule update --init --recursive

Then I rebuilt the tools for esp32s3.

**Comment by janick** [comment]
Never hit that one. I rolled back using:

```
% git checkout v5.0.2
% git submodule update
% ./install.sh esp32s3
```

**Comment by Moktarino** [comment]
Looks like that was it, thank you!!
Also, thank you for this repo!!!
